development: 
  database: blog_development
  host: 127.0.0.1
  port: 3306
  username: drujensen
  password: 

test: 
  database: blog_test
  host: 127.0.0.1
  port: 3306
  username: drujensen
  password: 

production: 
  database: blog
  host: 127.0.0.1
  port: 3306
  username: drujensen
  password: 
