development:
  mysql:
    database: blog_development
    host: 127.0.0.1
    port: 3306
    username: drujensen
    password: 

test:
  mysql:
    database: blog_test
    host: 127.0.0.1
    port: 3306
    username: blog_user
    password: 

production: 
  mysql:
    database: blog
    host: 127.0.0.1
    port: 3306
    username: drujensen
    password: 
